language: node_js
node_js:
  - "8"

script:
  - npm run build
  - npm run test

after_success:
  - cat ./coverage/lcov.info | npx coveralls

notifications:
  email:
    on_success: never

cache: yarn
